---
apiVersion: v1
kind: Namespace
metadata:
  name: stackrox
---
apiVersion: v1
kind: Namespace
metadata:
  name: stackrox-staging
---
apiVersion: v1
kind: Namespace
metadata:
  name: stackrox-cluster-channel
# ---
# apiVersion: v1
# data:
#   .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL3N0YWNrcm94LmlvIjp7ImF1dGgiOiIifX19Cg==
# kind: Secret
# metadata:
#   annotations:
#     apps.open-cluster-management.io/deployables: "true"
#   name: stackrox
#   namespace: stackrox-staging
# type: kubernetes.io/dockerconfigjson
# ---
# apiVersion: v1
# data:
#   .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2NvbGxlY3Rvci5zdGFja3JveC5pbyI6eyJhdXRoIjoiIn19fQo=
# kind: Secret
# metadata:
#   annotations:
#     apps.open-cluster-management.io/deployables: "true"
#   name: collector-stackrox
#   namespace: stackrox-staging
# type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
data:
  admission-control-cert.pem: Ii0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLVxuTUlJQ3dEQ0NBbWFnQXdJQkFnSUlBWmZ1ZnIydjVmQXdDZ1lJS29aSXpqMEVBd0l3UnpFbk1DVUdBMVVFQXhNZVxuVTNSaFkydFNiM2dnUTJWeWRHbG1hV05oZEdVZ1FYVjBhRzl5YVhSNU1Sd3dHZ1lEVlFRRkV4TTFNVGd4T0RNd1xuTlRZME1qSXhOREEwTmpNM01CNFhEVEl4TURjeU9ERTRNamt3TUZvWERUSXlNRGN5T0RFNU1qa3dNRm93Z2JveFxuTFRBckJnTlZCQW9USkRjMk5tUmtOV1U1TFRWa01EWXRORFpqWkMwNE4yUmpMV1V6WW1KaU5UWmlPR1F4WkRFaVxuTUNBR0ExVUVDd3daUVVSTlNWTlRTVTlPWDBOUFRsUlNUMHhmVTBWU1ZrbERSVEZJTUVZR0ExVUVBd3cvUVVSTlxuU1ZOVFNVOU9YME5QVGxSU1QweGZVMFZTVmtsRFJUb2dNREF3TURBd01EQXRNREF3TUMwd01EQXdMVEF3TURBdFxuTURBd01EQXdNREF3TURBd01Sc3dHUVlEVlFRRkV4SXhNVFE0TWpJMU5ETTJNelk1TkRnME5qUXdXVEFUQmdjcVxuaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFSVVlEempWQkUvdGgza0l2ZGxaUm1NcWYxcmd1YW9UNmVNSDdPOFxucHBobkpYbVR3VThMRUJHdFZhMXA5aDJLZ1RTTE1yUGFGSmcyZmtRKzA4bmhwSVRMbzRISE1JSEVNQTRHQTFVZFxuRHdFQi93UUVBd0lGb0RBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdEQVlEVlIwVFxuQVFIL0JBSXdBREFkQmdOVkhRNEVGZ1FVODZPSUlwdFAvN0lJZTNGV2pSWmVGTzBic1Bjd0h3WURWUjBqQkJnd1xuRm9BVWxORkpjZURodlVoWmxqNGkzNXRreFpKZmVWSXdSUVlEVlIwUkJENHdQSUlhWVdSdGFYTnphVzl1TFdOdlxuYm5SeWIyd3VjM1JoWTJ0eWIzaUNIbUZrYldsemMybHZiaTFqYjI1MGNtOXNMbk4wWVdOcmNtOTRMbk4yWXpBS1xuQmdncWhrak9QUVFEQWdOSUFEQkZBaUVBK1RTV0x5b3J2dHNKSEpXQ3Fmd242dHNvMjFEL0pLNVRTQ256ZUxQWlxuV2ZNQ0lHWnc2M2FDaDdQSnFHRldreVZpaFJwaVFhb1NoSFpEN2dwZnpNT2d2YnlrXG4tLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tXG4iCg==
  admission-control-key.pem: Ii0tLS0tQkVHSU4gRUMgUFJJVkFURSBLRVktLS0tLVxuTUhjQ0FRRUVJQzJqaU5YSUpsci9oZS9YUGFBQUhudDIzUCtKNEtYNXN5ZEZqbVR3OVZjUW9Bb0dDQ3FHU000OVxuQXdFSG9VUURRZ0FFVkdBODQxUVJQN1lkNUNMM1pXVVpqS245YTRMbXFFK25qQit6dkthWVp5VjVrOEZQQ3hBUlxuclZXdGFmWWRpb0UwaXpLejJoU1lObjVFUHRQSjRhU0V5dz09XG4tLS0tLUVORCBFQyBQUklWQVRFIEtFWS0tLS0tXG4iCg==
  ca.pem: Ii0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLVxuTUlJQjB6Q0NBWGlnQXdJQkFnSVVRVnRta2VHS3k5anFWdnJxWTFkR3YzN2NocEF3Q2dZSUtvWkl6ajBFQXdJd1xuUnpFbk1DVUdBMVVFQXhNZVUzUmhZMnRTYjNnZ1EyVnlkR2xtYVdOaGRHVWdRWFYwYUc5eWFYUjVNUnd3R2dZRFxuVlFRRkV4TTFNVGd4T0RNd05UWTBNakl4TkRBME5qTTNNQjRYRFRJeE1EY3lOekl5TURrd01Gb1hEVEkyTURjeVxuTmpJeU1Ea3dNRm93UnpFbk1DVUdBMVVFQXhNZVUzUmhZMnRTYjNnZ1EyVnlkR2xtYVdOaGRHVWdRWFYwYUc5eVxuYVhSNU1Sd3dHZ1lEVlFRRkV4TTFNVGd4T0RNd05UWTBNakl4TkRBME5qTTNNRmt3RXdZSEtvWkl6ajBDQVFZSVxuS29aSXpqMERBUWNEUWdBRXNHdEZPMXhSUUpIRkJyOTZiNGtuWlBLM3Bib21hZ0t2U01kMTlhOE5tbzNnVjRvNFxuaTlMYllrR3pDTkJWUkU2ZEY1SjJXakkyY29JKzRmVjZrQmkzdGFOQ01FQXdEZ1lEVlIwUEFRSC9CQVFEQWdFR1xuTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3SFFZRFZSME9CQllFRkpUUlNYSGc0YjFJV1pZK0l0K2JaTVdTWDNsU1xuTUFvR0NDcUdTTTQ5QkFNQ0Ewa0FNRVlDSVFDdTM1L0tWZkJWNCtQRXpFcWRyMFBsTmJDNEprb09nQm1wbWV0blxuMmM1aGJBSWhBTEJWb1NqREhaeHYrdVdiU2hxbkhodjJNV3pBZjJwQWROekN2c1Ftdy9mT1xuLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLVxuIgo=
kind: Secret
metadata:
  annotations:
    apps.open-cluster-management.io/deployables: "true"
  name: admission-control-tls
  namespace: stackrox-staging
type: Opaque
---
apiVersion: v1
data:
  collector-cert.pem: Ii0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLVxuTUlJQ29qQ0NBa2VnQXdJQkFnSUlicWZ5b0J5bWNBUXdDZ1lJS29aSXpqMEVBd0l3UnpFbk1DVUdBMVVFQXhNZVxuVTNSaFkydFNiM2dnUTJWeWRHbG1hV05oZEdVZ1FYVjBhRzl5YVhSNU1Sd3dHZ1lEVlFRRkV4TTFNVGd4T0RNd1xuTlRZME1qSXhOREEwTmpNM01CNFhEVEl4TURjeU9ERTRNamt3TUZvWERUSXlNRGN5T0RFNU1qa3dNRm93Z2FzeFxuTFRBckJnTlZCQW9USkRjMk5tUmtOV1U1TFRWa01EWXRORFpqWkMwNE4yUmpMV1V6WW1KaU5UWmlPR1F4WkRFYVxuTUJnR0ExVUVDd3dSUTA5TVRFVkRWRTlTWDFORlVsWkpRMFV4UURBK0JnTlZCQU1NTjBOUFRFeEZRMVJQVWw5VFxuUlZKV1NVTkZPaUF3TURBd01EQXdNQzB3TURBd0xUQXdNREF0TURBd01DMHdNREF3TURBd01EQXdNREF4SERBYVxuQmdOVkJBVVRFemM1TnpNMk1EZzBNelEzTnpJeE1URXpOalF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQlxuQndOQ0FBU25uZFhJNjJZcDlQamdOcStmdTBXWDg2d0tQY3lrSUJQQ0FMUURDTW85aUpDUVZGUlhEbDhSOUUySVxuYUdzdG54clpZQ1I1aUhLSEJjYXlySkxaMFRURm80RzNNSUcwTUE0R0ExVWREd0VCL3dRRUF3SUZvREFkQmdOVlxuSFNVRUZqQVVCZ2dyQmdFRkJRY0RBUVlJS3dZQkJRVUhBd0l3REFZRFZSMFRBUUgvQkFJd0FEQWRCZ05WSFE0RVxuRmdRVXFoZHE2ZndTT0JjWEJhLzBFQm1IZzNXb00wOHdId1lEVlIwakJCZ3dGb0FVbE5GSmNlRGh2VWhabGo0aVxuMzV0a3haSmZlVkl3TlFZRFZSMFJCQzR3TElJU1kyOXNiR1ZqZEc5eUxuTjBZV05yY205NGdoWmpiMnhzWldOMFxuYjNJdWMzUmhZMnR5YjNndWMzWmpNQW9HQ0NxR1NNNDlCQU1DQTBrQU1FWUNJUUNlU2xNRXA4Tlg0U1M2eVVCQVxuRVhZQWFxdGVmZ1d5c0lFcHhHRG5sTlY0QmdJaEFOd1Q3bVFSMGdHVGNGdnhmWmJ0U2UvVm5nYWkwZjdmanJpMVxuRWFZTjRuT1Vcbi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS1cbiIK
  collector-key.pem: Ii0tLS0tQkVHSU4gRUMgUFJJVkFURSBLRVktLS0tLVxuTUhjQ0FRRUVJRWxQNUk1eERFbFdoZ1lrVEd2NG9na1cvbTk3UzhIeGtJOS9zaDJEZE5zZm9Bb0dDQ3FHU000OVxuQXdFSG9VUURRZ0FFcDUzVnlPdG1LZlQ0NERhdm43dEZsL09zQ2ozTXBDQVR3Z0MwQXdqS1BZaVFrRlJVVnc1ZlxuRWZSTmlHaHJMWjhhMldBa2VZaHlod1hHc3F5UzJkRTB4UT09XG4tLS0tLUVORCBFQyBQUklWQVRFIEtFWS0tLS0tXG4iCg==
  ca.pem: Ii0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLVxuTUlJQjB6Q0NBWGlnQXdJQkFnSVVRVnRta2VHS3k5anFWdnJxWTFkR3YzN2NocEF3Q2dZSUtvWkl6ajBFQXdJd1xuUnpFbk1DVUdBMVVFQXhNZVUzUmhZMnRTYjNnZ1EyVnlkR2xtYVdOaGRHVWdRWFYwYUc5eWFYUjVNUnd3R2dZRFxuVlFRRkV4TTFNVGd4T0RNd05UWTBNakl4TkRBME5qTTNNQjRYRFRJeE1EY3lOekl5TURrd01Gb1hEVEkyTURjeVxuTmpJeU1Ea3dNRm93UnpFbk1DVUdBMVVFQXhNZVUzUmhZMnRTYjNnZ1EyVnlkR2xtYVdOaGRHVWdRWFYwYUc5eVxuYVhSNU1Sd3dHZ1lEVlFRRkV4TTFNVGd4T0RNd05UWTBNakl4TkRBME5qTTNNRmt3RXdZSEtvWkl6ajBDQVFZSVxuS29aSXpqMERBUWNEUWdBRXNHdEZPMXhSUUpIRkJyOTZiNGtuWlBLM3Bib21hZ0t2U01kMTlhOE5tbzNnVjRvNFxuaTlMYllrR3pDTkJWUkU2ZEY1SjJXakkyY29JKzRmVjZrQmkzdGFOQ01FQXdEZ1lEVlIwUEFRSC9CQVFEQWdFR1xuTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3SFFZRFZSME9CQllFRkpUUlNYSGc0YjFJV1pZK0l0K2JaTVdTWDNsU1xuTUFvR0NDcUdTTTQ5QkFNQ0Ewa0FNRVlDSVFDdTM1L0tWZkJWNCtQRXpFcWRyMFBsTmJDNEprb09nQm1wbWV0blxuMmM1aGJBSWhBTEJWb1NqREhaeHYrdVdiU2hxbkhodjJNV3pBZjJwQWROekN2c1Ftdy9mT1xuLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLVxuIgo=
kind: Secret
metadata:
  annotations:
    apps.open-cluster-management.io/deployables: "true"
  name: collector-tls
  namespace: stackrox-staging
type: Opaque
---
apiVersion: v1
data:
  sensor-cert.pem: Ii0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLVxuTUlJQ3N6Q0NBbG1nQXdJQkFnSUpBSVFRaDl6WG1CSWJNQW9HQ0NxR1NNNDlCQU1DTUVjeEp6QWxCZ05WQkFNVFxuSGxOMFlXTnJVbTk0SUVObGNuUnBabWxqWVhSbElFRjFkR2h2Y21sMGVURWNNQm9HQTFVRUJSTVROVEU0TVRnelxuTURVMk5ESXlNVFF3TkRZek56QWVGdzB5TVRBM01qZ3hPREk1TURCYUZ3MHlNakEzTWpneE9USTVNREJhTUlHbFxuTVMwd0t3WURWUVFLRXlRM05qWmtaRFZsT1MwMVpEQTJMVFEyWTJRdE9EZGtZeTFsTTJKaVlqVTJZamhrTVdReFxuRnpBVkJnTlZCQXNNRGxORlRsTlBVbDlUUlZKV1NVTkZNVDB3T3dZRFZRUURERFJUUlU1VFQxSmZVMFZTVmtsRFxuUlRvZ01EQXdNREF3TURBdE1EQXdNQzB3TURBd0xUQXdNREF0TURBd01EQXdNREF3TURBd01Sd3dHZ1lEVlFRRlxuRXhNNU5URTJNalUxTXprMU1qRXpORGd3TkRjMU1Ga3dFd1lIS29aSXpqMENBUVlJS29aSXpqMERBUWNEUWdBRVxudHhNOElOZFVxWWhZSEk1L2RvcWgxc0JSZnNhTUp5YzFodWlFWFJHTmNDYXJZNEIxeStyeTVJdCtiK0x0K2o0a1xuQTlwczdkSTVoRFFZMktHaWgvNlEwNk9CempDQnl6QU9CZ05WSFE4QkFmOEVCQU1DQmFBd0hRWURWUjBsQkJZd1xuRkFZSUt3WUJCUVVIQXdFR0NDc0dBUVVGQndNQ01Bd0dBMVVkRXdFQi93UUNNQUF3SFFZRFZSME9CQllFRkRqY1xuREJVV3ZKeERuQzZIVlNCQk5sbzRENE1hTUI4R0ExVWRJd1FZTUJhQUZKVFJTWEhnNGIxSVdaWStJdCtiWk1XU1xuWDNsU01Fd0dBMVVkRVFSRk1FT0NEM05sYm5OdmNpNXpkR0ZqYTNKdmVJSVRjMlZ1YzI5eUxuTjBZV05yY205NFxuTG5OMlk0SWJjMlZ1YzI5eUxYZGxZbWh2YjJzdWMzUmhZMnR5YjNndWMzWmpNQW9HQ0NxR1NNNDlCQU1DQTBnQVxuTUVVQ0lRREpKZ3Z0SmhWcEVCZUttb0lRVEg0REFMM1FXczZSNlhpcXJQalRqd2x6MlFJZ0NDc3Q4Q2RNM0NDaFxuaFl0YmJ6TG9FWS9TTzNKQW1rd0V1a05IMVhKaEU2OD1cbi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS1cbiIK
  sensor-key.pem: Ii0tLS0tQkVHSU4gRUMgUFJJVkFURSBLRVktLS0tLVxuTUhjQ0FRRUVJSlFYZnNycGR0NUhmZy9MMVdOa0orL3Y1dVVlcklBUmxEVC9ad0dLV1lGam9Bb0dDQ3FHU000OVxuQXdFSG9VUURRZ0FFdHhNOElOZFVxWWhZSEk1L2RvcWgxc0JSZnNhTUp5YzFodWlFWFJHTmNDYXJZNEIxeStyeVxuNUl0K2IrTHQrajRrQTlwczdkSTVoRFFZMktHaWgvNlEwdz09XG4tLS0tLUVORCBFQyBQUklWQVRFIEtFWS0tLS0tXG4iCg==
  ca.pem: Ii0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLVxuTUlJQjB6Q0NBWGlnQXdJQkFnSVVRVnRta2VHS3k5anFWdnJxWTFkR3YzN2NocEF3Q2dZSUtvWkl6ajBFQXdJd1xuUnpFbk1DVUdBMVVFQXhNZVUzUmhZMnRTYjNnZ1EyVnlkR2xtYVdOaGRHVWdRWFYwYUc5eWFYUjVNUnd3R2dZRFxuVlFRRkV4TTFNVGd4T0RNd05UWTBNakl4TkRBME5qTTNNQjRYRFRJeE1EY3lOekl5TURrd01Gb1hEVEkyTURjeVxuTmpJeU1Ea3dNRm93UnpFbk1DVUdBMVVFQXhNZVUzUmhZMnRTYjNnZ1EyVnlkR2xtYVdOaGRHVWdRWFYwYUc5eVxuYVhSNU1Sd3dHZ1lEVlFRRkV4TTFNVGd4T0RNd05UWTBNakl4TkRBME5qTTNNRmt3RXdZSEtvWkl6ajBDQVFZSVxuS29aSXpqMERBUWNEUWdBRXNHdEZPMXhSUUpIRkJyOTZiNGtuWlBLM3Bib21hZ0t2U01kMTlhOE5tbzNnVjRvNFxuaTlMYllrR3pDTkJWUkU2ZEY1SjJXakkyY29JKzRmVjZrQmkzdGFOQ01FQXdEZ1lEVlIwUEFRSC9CQVFEQWdFR1xuTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3SFFZRFZSME9CQllFRkpUUlNYSGc0YjFJV1pZK0l0K2JaTVdTWDNsU1xuTUFvR0NDcUdTTTQ5QkFNQ0Ewa0FNRVlDSVFDdTM1L0tWZkJWNCtQRXpFcWRyMFBsTmJDNEprb09nQm1wbWV0blxuMmM1aGJBSWhBTEJWb1NqREhaeHYrdVdiU2hxbkhodjJNV3pBZjJwQWROekN2c1Ftdy9mT1xuLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLVxuIgo=
kind: Secret
metadata:
  annotations:
    apps.open-cluster-management.io/deployables: "true"
  name: sensor-tls
  namespace: stackrox-staging
type: Opaque
---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    apps.open-cluster-management.io/deployables: "true"
  name: acs-config
  namespace: stackrox-staging
data:
  acs-host: central-stackrox.apps.neil-openshift.sol.rox.systems:443
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: secured-cluster-resources
  namespace: stackrox-staging
spec:
  pathname: stackrox-staging
  type: Namespace
# ---
# apiVersion: apps.open-cluster-management.io/v1
# kind: Channel
# metadata:
#   name: acs-secured-cluster-services-ch
#   namespace: stackrox-cluster-channel
#   labels:
#     acm-app: acs-secured-cluster-services
# spec:
#   type: HelmRepo
#   pathname: https://charts.stackrox.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: secured-cluster-sub
  namespace: stackrox
spec:
  channel: stackrox-staging/secured-cluster-resources
  placement:
    placementRef:
      kind: PlacementRule
      name: secured-cluster-placement
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  namespace: stackrox
  name: stackrox-secured-cluster-services
  labels:
    acm-app: acs-secured-cluster-services
spec:
  name: stackrox-secured-cluster-services
  channel: stackrox-cluster-channel/acs-secured-cluster-services-ch
  packageFilter:
    version: 58.0.0
  packageOverrides:
    - packageName: stackrox-secured-cluster-services
      packageAlias: secured-cluster-services
  placement:
    placementRef:
      name: secured-cluster-placement
      kind: PlacementRule
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: secured-cluster-placement
  namespace: stackrox
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector: {}
---
